### ISSUE TITLE
Consistent naming of customisation mixins

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-proposals#14]
## What

We've identified that the mixins our components use for customisation are inconsistent. We'd like to address this by deciding on some rules for mixin naming. This may make it into the specification at some point.

## Why

The inconsistency makes documentation less readable, and components less intuitive to use. Particularly the conflicting terminology of `custom` and `customize`, which is now part of o-brand.

## Supporting Examples

We've identified that there are two kinds of customisation for components:

  1. Customising existing things. E.g. making all primary buttons everywhere a different colour (including where they're used by other components)

  2. Adding _new_ things. E.g. creating a new class with a hot pink button

Examples of where we use these now:

  - o-buttons:
    - `oButtonsTheme`: [type 2]
    - `oButtonsCustomTheme`: [type 2] (deprecated)
    - `oButtonsIconButton`: [type 2]
  - o-header-services:
    - `oHeaderServicesCustomize`: [type 1] (delegates to `oBrandCustomize`)
  - o-labels:
    - `oLabelsAddState`: [type 2]
  - o-typography:
    - `oTypographyCustomLink`: [type 2]
    - `oTypographyCustomize`: [type 1] (delegates to `oBrandCustomize`)
  - multiple components:
    - `oColorsSetUseCase`: [type 1]
  - o-forms:
    - `oFormsRadioButtonsStyledTheme`: [type 2]
    - `oFormsRadioButtonsStyledIcon`: [type 2]
  - o-forms v7:
    - `oFormsCustom`: [type 2]

## Questions

  - Should all type 2 customizations include a modifier class in the output (e.g. o-labels)?
  - What should the convention be around type 1 vs type 2 naming?

**Comment by rowanmanning** [comment]
We discussed this in person, here's a summary:

## Should all type 2 customizations include a modifier class in the output (e.g. o-labels)?

**Discussion:**

  - Labels includes a modifier class in the output, it's named `.o-labels--{statename}`
  - Con: Maybe this is a little bit magic, do you know what the class will be? Requires attention to documentation
  - Pro: Identifiable as part of an Origami component
  - No guarantee but should hopefully encourage reuse rather than outputting multiple times
  - We definitely need consistency

**Decision:**

Yes, we should output the classes ourselves but they must be prefixed with the component name (like o-labels). Content mixins are an exception, but these always end in `Content`. So the rule is, always output a class name unless the mixin ends in `Content`.

## What should the convention be around type 1 vs type 2 naming?

**Discussion:**

  - Although we use `oWhateverCustomize`, this could change with some deprecations
  - We use "add" in o-labels, to indicate a new class being output. Could be used in o-forms potentially, but `oFormsAddCustom(input)`?
  - If we go with "add" it should be qualified, we don't thing `oWhateverAdd` is descriptive/intuitive by itself
  - Should the term "theme" go away? No – sometimes it works
  - If we keep the "add" mixins descriptive, then there's not really a need for "custom" (which can be confused with "customize" – a branding thing)

**Decision:**

  - Type 1 customizations use `oWhateverCustomize` which uses `oBrandCustomize`
  - Type 2 customizations use `oWhateverAddSomething` and always output a new modifier class prefixed with `o-whatever--`
  - Content-only mixins use `oWhateverContent` – this should be the only content mixin

**Comment by notlee** [comment]
We also touched on `oColorsSetUseCase`. It will probably go away in the future, replaced by `oWhateverCustomize`

**Comment by notlee** [comment]
Whilst working on a typography proposal it become clear that the proposed `Content` mixin convention becomes problematic when there are many content mixins. It's difficult to see at a glance what the mixins are for as the most important piece of information is in the middle of the name. Instead we're considering `oComponentContentWhatever`.

E.g. instead of this:
```
oEditorialTypographyBodyContent
oEditorialTypographyListContent
oEditorialTypographyFooterContent
oEditorialTypographyCaptionContent
oEditorialTypographyHeadlineContent
oEditorialTypographyHeadingContent
oEditorialTypographyTimestampContent
oEditorialTypographyStandfirstContent
oEditorialTypographyTagContent
oEditorialTypographyAuthorContent
oEditorialTypographyTopicContent
```

name like this:
```
oEditorialTypographyContentBody
oEditorialTypographyContentList
oEditorialTypographyContentFooter
oEditorialTypographyContentCaption
oEditorialTypographyContentHeadline
oEditorialTypographyContentHeading
oEditorialTypographyContentTimestamp
oEditorialTypographyContentStandfirst
oEditorialTypographyContentTag
oEditorialTypographyContentAuthor
oEditorialTypographyContentTopic
```

**Comment by notlee** [comment]
https://github.com/Financial-Times/origami-proposals/issues/14#issuecomment-527999699

Further to this we decided to kill the `Content` mixin naming convention. It's too verbose. The `oWhateverCustomize` and `oWhateverAddSomething` elements of this proposal re still being taken forward.

**Comment by notlee** [comment]
> **Decision:**
> 
>     * Type 1 customizations use `oWhateverCustomize` which uses `oBrandCustomize`
> 
>     * Type 2 customizations use `oWhateverAddSomething` and always output a new modifier class prefixed with `o-whatever--`
> 
>     * Content-only mixins use `oWhateverContent` – this should be the only content mixin

All Origami maintained components now follow the `oWhateverCustomize` and `oWhateverAddSomething` naming conventions. In practice we found `oWhateverContent` to be frustratingly verbose and dropped it.

To close this issue I think `oWhateverCustomize` and `oWhateverAddSomething` need to be added to the spec as a `should`, if we're happy with how they turned out?

**Comment by JakeChampion** [comment]
> To close this issue I think `oWhateverCustomize` and `oWhateverAddSomething` need to be added to the spec as a `should`, if we're happy with how they turned out?

@notlee, I'm happy with us adding that to the spec. @Financial-Times/origami-core, what do you all think?

**Comment by chee** [comment]
that seems fine
