### ISSUE TITLE
meter component

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-proposals#15]
## What

A [meter](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter) component.

## Why

A meter of similar style appears to be duplicated by multiple projects across multiple teams.

## Supporting Examples

[Loadstar (lodestar.ft.com)](https://lodestar.ft.com/):
<img width="688" alt="Screenshot 2019-05-20 at 17 29 53" src="https://user-images.githubusercontent.com/10405691/58037379-3550b980-7b25-11e9-89ee-13bff87e5e48.png">

[System Operability Score (sos.in.ft.com)](https://sos.in.ft.com/):
<img width="768" alt="Screenshot 2019-05-20 at 17 26 18" src="https://user-images.githubusercontent.com/10405691/58037387-3e418b00-7b25-11e9-8419-8061d3420f97.png">

[Prospector (google slides)](https://docs.google.com/presentation/d/1AnSHxu9mgAXAJ3-ls-Nq__RUNmA_wLZyY61NY0VRwgk/edit#slide=id.g5a2463afc9_2_18):
<img width="320" alt="Screenshot 2019-05-20 at 17 27 03" src="https://user-images.githubusercontent.com/10405691/58037472-6630ee80-7b25-11e9-963e-526372794269.png">

**Comment by lucas42** [comment]
Just wanted to add that the Single System View is now also using a meter component:
![image](https://user-images.githubusercontent.com/428847/71832667-527dcc80-30a3-11ea-9c83-cd685acd2557.png)

https://ssv.in.ft.com/migrations

Much of the styling was originally copy/pasted from SOS but has now diverged somewhat, so I think an origami component would be really useful here.

**Comment by lucas42** [comment]
I've added a variant of the meter component in SSV.  
These are smaller meters which are coloured based on a particular service tier.  The colour of the progress bar matches the service tier's colour (though that means the background can't be grey any more as it's too close to silver & platinum).  I've also hidden the progress numbers until you hover over these.

![image](https://user-images.githubusercontent.com/428847/72435004-fa2a8700-3794-11ea-85e2-69ec988196cf.png)

https://ssv.in.ft.com/migrations

Not sure how many other places would use this particular variant, but being able to extend the base meter component in such a way would be really useful.

**Comment by lucas42** [comment]
Source code for SSV examples:
https://github.com/Financial-Times/single-system-view/blob/master/src/templates/components/migration-list.jsx#L3-L46
https://github.com/Financial-Times/single-system-view/blob/master/src/browser/_meter.scss
