### ISSUE TITLE
Proposal: add a new "assigned" or "prioritised" column to our board

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-proposals#22]
## What

I think we should add a column between "incoming" and "active" on our [project board](https://github.com/orgs/Financial-Times/projects/83). This column should be manually prioritised and only contain issues that have been assigned to somebody.

This would mean:
- "incoming" = the fire hose of everything that comes into our repos
- "assigned" or "prioritised" = things we've decided to work on
- "active" = things we are currently working on
- "complete" = things we have completed

## Why

New issues get added to the _top_ of the "Incoming" column which can be noisy and drown out things that we'd manually pushed to the top. This adds an amount of friction to grooming and opens up the possibility for things to get a bit lost.

**Comment by wheresrhys** [comment]
![image](https://user-images.githubusercontent.com/447559/74541514-a8168600-4f39-11ea-9652-1f1e0d43fd29.png) :trollface:

**Comment by chee** [comment]
That's how i've been using the active column

**Comment by chee** [comment]
(i.e., it contains things i'm planning on doing between now and the next planning meeting)

**Comment by chee** [comment]
If we aren't planning on working on something I think we should close the issue.
If we're working on it this cycle then I think it's good for it to be in the `active` column.

if the problem is that things are being added to the top of the incoming column, we can change it so they get added to the bottom

**Comment by notlee** [comment]
The problem is that we have issues coming in that we should prioritise but haven't been picked up by anyone yet. It would be great to separate those so they don't get buried by less important issues between backlog grooming

**Comment by chee** [comment]
What are "less important issues"? Where are they coming from? How will we stop them from burying the important issues in a new column?

**Comment by chee** [comment]
Is this about issues that aren't important enough to start working on right now, but need to be prioritised at some point, and it's very important that we prioritise them at the next meeting? If that's the case i think we should use a label

**Comment by rowanmanning** [comment]
I think maybe we need to have a grooming session with the whole team before we change anything 🙂 happy to leave this for now and make no changes until we've done this.

The issues that I was seeing as noise when I'm in a "grooming" context rather than a "day-to-day work" context are things like the dependabot bumps. But let's discuss next Friday.

**Comment by chee** [comment]
If we aren't interested in seeing the dependabot bumps we can make it so dependabot bumps are moved to the bottom of incoming instead of the top.
the dependabot issues is still work that somebody on the team needs to do, though. it's still time that needs to be found, and i personally appreciate seeing them.

**Comment by rowanmanning** [comment]
Let's continue as we are for now, and use labels or filtering by assigned issues.
