### ISSUE TITLE
Remove the ability to customise classes across components

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/origami-proposals#4]
## What

The ability to customise classes has not been consistent across our components. We want to create consistency, so are opening this discussion to figure out whether we should remove the customisation, or add it to all components.

Currently we are leaning toward removing the ability to customise.

## Why

- More readable SCSS and simpler JS.
- Mixins can be used to include features without needing to wrap mixins in classes.
- Encourages CSS reuse including a component once rather than multiple times with different class names.
- Increase reliability and maintainability

**Comment by rowanbeentje** [comment]
What's the ability to customise classes - got a short example or the calls used by the components which do support it?  Is this like the `new Overlay('overlay', { class: 'o-overlay--my-modifier' })` which *adds* an extra class to enable more targeting, or something else?

**Comment by gvonkoss** [comment]
🙈and 🤔  
we were referring to situations like: 
```
@include oMessage($class: my-message) 

//output
.my-message {
    property: value;
}
``` 
I think it would involve some work to break out modifiers and such, but we're trying to get a feel for the general consensus

**Comment by dan-searle** [comment]
I'm in favour of removing this ability. Is there a particular use case it was introduced for?

**Comment by notlee** [comment]
@dan-searle Not that's known to me. It might be useful for using a component to build a new component, but we can still provide mixins which include no classes, [oNormaliseVisuallyHidden](https://github.com/Financial-Times/o-normalise/blob/master/src/scss/_mixins.scss#L3) is a good example .

**Comment by i-like-robots** [comment]
I'm in favour of removing this too because it seems obtuse and is little, if ever, used.

**Comment by rowanmanning** [comment]
Had a quick chat with @wheresrhys on this, wondered whether he'd have some history. We came up with some potential reasons why you _might_ do this:

  - class name shortening
  - vanity
  - retrofitting origami to sites where the dev has limited ability to edit the html

Going to look through some old issues and commits to see if I can find the real reasons

**Comment by notlee** [comment]
>retrofitting origami to sites where the dev has limited ability to edit the html
Good thoughts. That sounded like a compelling reason but actually doesn't _really_ apply here as usually we only allow modifying the block portion of the class, not element or modifier portions.

**Comment by notlee** [comment]
For the reasons above, we're decided to start removing the ability to customise the base class of Origami components. Thanks for your input everyone 👍

**Comment by notlee** [comment]
This was done. No Origami maintained components allow class customisation in this way. I don't think it's something to specially spec against though, especially if we spec how we should customise components, and would like to close this issue. Thoughts @Financial-Times/origami-core?

**Comment by JakeChampion** [comment]
@notlee Agree, let's close this :-)
